import { Providers } from "@/components/Providers";
import { Header } from "@/components/Header";
import { nunito } from "@/components/Fonts";
import getCurrentUser from "./actions/getCurrentUser";

import "@/styles/global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const currentUser = await getCurrentUser();
  console.log(currentUser)
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
